language: go

sudo: false

services:
  - docker

go:
  - "1.12"

before_install:
  - GO111MODULE=off go get github.com/golang/dep/cmd/dep
  - git clone --branch=v0.10.x --depth=1 https://github.com/operator-framework/operator-sdk $GOPATH/src/github.com/operator-framework/operator-sdk && pushd $GOPATH/src/github.com/operator-framework/operator-sdk && GO111MODULE=on go install ./cmd/operator-sdk && popd

env:
  - TARGET=unit-verbose
  - TARGET=lint
  - TARGET=docker

script: GO111MODULE=off make $TARGET
