name: Periodic E2E Test Optional

on:
  schedule:
    # Run every day at 04:20 UTC (it is recommended to avoid running at the start of the hour)
    - cron: '20 4 * * *'

permissions: {}

jobs:
  periodic-e2e-test-optional:
    strategy:
      fail-fast: false
      matrix:
        bmc-protocol:
        - redfish
        - redfish-virtualmedia
        - ipmi
    uses: ./.github/workflows/e2e-test.yml
    with:
      bmc-protocol: ${{ matrix.bmc-protocol }}
      ginkgo-focus: upgrade
    permissions:
      contents: read
