name: E2E Test

on:
  pull_request:
    branches:
    - 'main'
    - 'release-*'
    paths-ignore:
    - '**/*.md'
    - 'docs/**'
    - '.gitignore'
    - 'hack/*.sh'
    - 'LICENSE'
    - 'SECURITY_CONTACTS'
    - 'DCO'
    - 'OWNERS'

permissions: {}

jobs:
  e2e-test:
    strategy:
      fail-fast: false
      matrix:
        bmc-protocol:
        - redfish-virtualmedia
        - ipmi
    uses: ./.github/workflows/e2e-test.yml
    with:
      bmc-protocol: ${{ matrix.bmc-protocol }}
    permissions:
      contents: read
