name: release

on:
  push:
    # Sequence of patterns matched against refs/tags
    tags:
    - "v*"

permissions: {}

jobs:
  build:
    name: tag release
    runs-on: ubuntu-latest

    permissions:
      contents: write

    if: github.repository == 'metal3-io/baremetal-operator'
    steps:
    - name: Export RELEASE_TAG var
      run: echo "RELEASE_TAG=${GITHUB_REF:10}" >> $GITHUB_ENV
    - name: checkout code
      uses: actions/checkout@0ad4b8fadaa221de15dcec353f45205ec38ea70b # v4.1.4
      with:
        fetch-depth: 0
    - name: Install go
      uses: actions/setup-go@cdcb36043654635271a94b9a6d1392de5bb323a7 # v5.0.1
      with:
        go-version: '1.22'
    - name: Generate release notes
      run: |
        make release-notes
    - name: Release
      uses: softprops/action-gh-release@69320dbe05506a9a39fc8ae11030b214ec2d1f87 # v2.0.5
      with:
        draft: true
        files: out/*
        body_path: releasenotes/${{ env.RELEASE_TAG }}.md
